### ISSUE TITLE
C++ bindings: Add bool operator to classes to check for null handle

### ISSUE THREAD

**Issue by fsahmad** [Autodesk/AutomaticComponentToolkit#64]
I'm using ACT 1.5.0, on win/mac platforms using C++ dynamic bindings.

In our component, we have some functions that return nullptr instead of throwing exceptions, but checking for this when using C++ bindings is a bit counter-intuitive as you need to check the _handle_. 

For example, for a component function like this:
```c++
IFoo *OpenFoo(const std::string& sPath) {
    IFoo *pFoo = nullptr;

    if (exists(sPath)) {
        pFoo = new CFoo(sPath);
    }

    return pFoo;
}
```

you'd have to check the returned object like this:
```c++
IFoo *pFoo = CWrapper::OpenFoo("path/to/foo");
if (pFoo->GetHandle()){
  // do something
}
```

where in C++ you're more likely to write:
```c++
IFoo *pFoo = CWrapper::OpenFoo("path/to/foo");
if (pFoo){
  // do something
}
```

I don't know how this is handled in the other bindings, or if there are some other considerations, but for C++ I think it would be very useful to overload the boolean cast which checks the handle.

**Comment by alexanderoster** [comment]
Hi there,

we use std::shared_ptrs for the handling of the memory, so the correct way to check things is

> if (pFoo.get()) {
> // do Something
> }

**Comment by fsahmad** [comment]
That's what I intuitively would expect, _but_ what actually happens is this (from the C++ binding header):

```c++
    inline PFoo CWrapper::OpenFoo(const std::string & sPath)
    {
        ComponentHandle hFoo = nullptr;
        CheckError(nullptr,m_WrapperTable.m_OpenFoo(sPath.c_str, &hFoo));
        return std::make_shared<CFoo>(this, hFoo);
    }
```

Note that this will _always_ allocate an instance of `CFoo`, just with a null handle. Although I created this issue suggesting a bool operator, it's probably better to just return an empty shared_ptr if the handle is null.

**Comment by alexanderoster** [comment]
Ah, you are absolutely right, this of course is a problem. We will fix the behaviour as soon as possible.

**Comment by martinweismann** [comment]
Hi @fsahmad, thanks for your interest in ACT

One comment in advance:
overloading the bool operator
```c++
class CBase {
// ...
	public:
	operator bool() {
		return !GetHandle();
	}
}
```
would result in this:
```c++
if (pFoo->GetHandle()) {
	// do something
}
// would be equivalent to
if (*pFoo) {
	// do something
}
```
thus there would be no direct confusion between
```c++
if (*pFoo) // checking for GetHandle()!=nullptr
```
and
```c++
if (pFoo) // checking whether the pointer pFoo is assigned.
```
So far so good.

**_however_**

Having said that, I disagree with overloading the boolean cast due to the following consideration:


If you create an instance of `Foo::CFoo` (on the wrapper side) like this
```c++
CFoo *pFoo = CWrapper::OpenFoo("path/to/foo");
```
you will have to manually track the lifetime of the objected `pFoo` points to. i.e. you will have to call 
```c++
delete pFoo;
```
which will internally call
```c++
wrapper->release(pFoo->m_pHandle);
```

On the implementation side it is fine to create `Foo::Impl::IFoo` (or `CFoo`) like this
```c++
IFoo *pFoo = OpenFoo("path/to/foo");
```
you will have to manually track the live time of the objected `pFoo` points to.
i.e. you will have to call 
```c++
delete pFoo;
```
In contrast to the binding side, `pFoo` does not have a member m_pHandle.

This illustrates that the `m_pHandle` itself is a member of the Foo::CFoo-object on the binding side which is the address of the
`Foo::Impl::CFoo`-object that was `newed` on the implementation side.


ACT advocates to that the m_pHandle variable should never be explicitly touched or queried in most languages bindings, only the lifetime of the `Foo::CFoo`-object matters.

ACT further recommends using exceptions instead of returning `nullptr` and checking against GetHandle() != nullptr for many reasons, e.g.
- by considering handle a private member of the Binding objects, that is tied to the livetime of the binding-object ownership and livetime of
the handle is very obvious and clear: it is the same as the ownership and livetime of the binding object.
- in the long term there can be many reasons why CWrapper::OpenFoo("path/to/foo") fails (or in your case returns a nullptr), e.g. file does not exist, file cannot be parsed, file is locked, ... 
- The Python and C#-bindings will directly throw exceptions if a <param type="class" pass="out"> returns a nullptr.

In fact, we intend to make the GetHandle-function protected at some point. The concept of "handle" should not exist in binding world.

Thus, ACT suggests the following pattern in most binding languages (Python, Pascal, CSharp, ..., except for plain C) : 
```c++
// application code that uses the C++-binding
// PFoo is defined in the C++-Binding via `typedef std::shared_ptr<CFoo> PFoo;`
try {
	PFoo pFoo = CWrapper::OpenFoo("path/to/foo");
	// do something
} catch (FooException &e ) {
	if (e.errorCode() == FOO_ERROR_PATHDOESNOTEXIST) {
		// do nothing, or log that file does not exist... 
	} else if (e.errorCode() == FOO_ERROR_INVALIDCONTENTOFFILE) {
		// do nothing, or log that file could not be parsed
	} else
		throw e;
}
```

The corresponding C++-Implementation side would then make `OpenFoo` a very simplistic factory-method:
```c++
IFoo *OpenFoo(const std::string& sPath) {
	std::unique_ptr<IFoo> pFoo(new CFoo());
	pFoo->OpenPath(sPath);	// If OpenFile throws any exceptions,
							// the unique ptr pFoo will clean up the newed memory when it goes out of scope,
							// while the exception itself is passed to the caller of OpenFoo
	return pFoo.release();	// release ownership of the newed CFoo-object and return it
}

void CFoo::OpenPath(const std::string& sPath) {
	if (exists(sPath)) {
		// read and parse the file
    }
	else
		throw EFooInterfaceException(FOO_ERROR_PATHDOESNOTEXIST);
}
```

**Comment by martinweismann** [comment]
Having said all of that, let me spend some time on looking into this issue a but more.

As @alexanderoster  pointed out to me earlier, there are use-cases that would benefit from the ability to return `nullptr`s, like
```c++
PFoo pFoo = pFooList->FindSomething("FooName);
```

A good alternative solution might be to enable `nullptr`-values for handles. Whenever a binding-object with `m_pHandle == nullptr` would be created. the binding object itself would not be created and instead a `shared_ptr<CFoo>(null)` will be created. This way, the only check required on binding side will always be 
```c++
PFoo pFoo = pFooList->FindSomething("FooName);
if (pFoo) {
// do Something
}
```
instead of 
```c++
if (pFoo) && (pFoo->GetHandle()){
// do Something
}
```
Similar adaptions can be made in the other bindings, too.

I think this would be a good path forward.

**Comment by martinweismann** [comment]
@fsahmad : https://github.com/Autodesk/AutomaticComponentToolkit/pull/67
introduces a new parametertype "optionalclass" that allows `return`ing, `out`putting or `in`putting classes that are `null` and changes most ACT bindings (C++, Pascal, Python) such that any creation of a `CFoo*` on client side with `CFoo*->GetHandle() == nullptr`  in fact creates `CFoo* pFoo = nullptr`. 

This will enter ACT 1.6.0.
